### ISSUE TITLE
Is it possible to exclude specific directories from linting?

### ISSUE THREAD

**Issue by SimonBalling** [ScaCap/action-ktlint#19]
Is it possible to exclude specific directories from linting?

ktlint itself does support this

**Comment by alsutton** [comment]
I've uploaded #29 which allows this. It's currently waiting on a review.

**Comment by ghaiszaher** [comment]
Closing as https://github.com/ScaCap/action-ktlint/pull/29 is merged, please reopen if it doesn't solve your problem.
