### ISSUE TITLE
Build fails with " Error: Docker build failed with exit code 3 ".

### ISSUE THREAD

**Issue by hirotask** [ScaCap/action-ktlint#34]
Hi. 

I have an issue like that:
Using the code in the [README.md](https://github.com/ScaCap/action-ktlint/blob/master/README.md#example-usage), I got the following error when running Actions.
```
  Step 5/7 : RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}
   ---> Running in 3b77dd471421
  reviewdog/reviewdog info checking GitHub for tag 'v0.14.1'
  reviewdog/reviewdog info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/Linux/x86_64
  The command '/bin/ash -eo pipefail -c wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}' returned a non-zero code: 3

Warning: Docker build failed with exit code 3, back off 5.742 seconds before retry.
...
Error: Docker build failed with exit code 3 
```

I'm sorry that my writing may be a little strange because I'm not a native English speaker.

**Comment by LemonDouble** [comment]
@hirotask I had the same error, but when I ran it again today, it magically worked. Could you try running the Actions again?

**Comment by ghaiszaher** [comment]
Looks related to https://github.com/reviewdog/reviewdog/issues/1380

**Comment by ghaiszaher** [comment]
Closing as the original issue seems to be resolved.
